// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkB2VhwjmknrAkaeakoF34CH_icuPSRiw',
    appId: '1:914950444280:android:12e240eaaf537280b0970d',
    messagingSenderId: '914950444280',
    projectId: 'fcm-dmo-c5ef0',
    storageBucket: 'fcm-dmo-c5ef0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqH4dkHiU_jLsHz2rzZieNtPUNUOtOUUE',
    appId: '1:914950444280:ios:e6159ef74a1cf052b0970d',
    messagingSenderId: '914950444280',
    projectId: 'fcm-dmo-c5ef0',
    storageBucket: 'fcm-dmo-c5ef0.appspot.com',
    androidClientId:
        '914950444280-u8v9ngfev8ral0i2ap9hpqjl39tomd12.apps.googleusercontent.com',
    iosClientId:
        '914950444280-l5q3unma5qndufeudv918kupcc5d1pak.apps.googleusercontent.com',
    iosBundleId: 'com.dmlt.dmoFlutter',
  );
}
